export enum LOGIN_STATUS {
  REQUEST = "LOGIN_REQUEST",
  SUCCESS = "LOGIN_SUCCESS",
  FAILURE = "LOGIN_FAILURE",
}
export enum REGISTER_STATUS {
  REQUEST = "REGISTER_REQUEST",
  SUCCESS = "REGISTER_SUCCESS",
  FAILURE = "REGISTER_FAILURE",
}
export enum LOGOUT_STATUS {
  REQUEST = "LOGOUT_REQUEST",
  SUCCESS = "LOGOUT_SUCCESS",
  FAILURE = "LOGOUT_FAILURE",
}

